apps/core/urls.py
"""urls"""

from django.conf import settings
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),

    path("account/", include("django.contrib.auth.urls")),
    path("matches", include("matches.urls")),
    path("goals", include("goals.urls")),
    path("api/v1/", include("api_v1.urls")),
]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

apps/matches/urls.py
"""urls"""
from django.urls import path

from .views import MatchListView, MatchDetailView

app_name = 'matches'

urlpatterns = [
    path("", MatchListView.as_view(), name="list"),
    path('<int:pk>/', MatchDetailView.as_view(), name='match-detail'),

]

apps/matches/models.py
"""models"""
import uuid as uuid_lib

from django.db import models
from django.utils.translation import gettext_lazy as _

from django_extensions.db.models import TimeStampedModel

from players.models import Player


class Match(TimeStampedModel):
    """A match between two teams."""

    opponent = models.CharField(
        verbose_name=_("opponent"),
        max_length=60)
    date = models.DateField(
        verbose_name=_("date"))
    home = models.BooleanField(
        verbose_name=_("home"))
    opponent_goals = models.PositiveIntegerField(
        verbose_name=_("opponent goals"),
        null=True)
    players = models.ManyToManyField(
        Player,
        related_name="matches",
        verbose_name=_("players"),
    )
    uuid = models.UUIDField( # Used by the API
        db_index=True,
        default=uuid_lib.uuid4,
        editable=False)
    class Meta:
        verbose_name = _("Match")
        verbose_name_plural = _("Matches")

    def __str__(self):
        return self.title

    @property
    def title(self):
        """Return match name (depending on home/away)."""
        if self.home:
            return f"DES 1 - {self.opponent}"
        return f"{self.opponent} - DES 1"

    @property
    def team_goals(self):
        """Returns number of goals scored by own team."""
        return self.goals.count()

    @property
    def score(self):
        """Returns match score."""
        if self.opponent_goals:
            if self.home:
                return f"{self.team_goals} - {self.opponent_goals}"
            return f"{self.opponent_goals} - {self.team_goals}"
        return _("no score yet")

apps/matches/views.py
"""views"""
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Match


class MatchListView(LoginRequiredMixin, ListView):
    """View for listing matches"""
    model = Match

class MatchDetailView(DetailView):
    """view for listing matches"""
    model = Match

    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}
        if self.object:
            context['goals'] = self.object.goals.all().select_related("player")
        return super().get_context_data(**context)

apps/templates/matches/match_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Match" %}{% endblock title %}

{% block content %}
    <h1>{{ object }}</h1>
    <br>
    <p><strong>{% trans "Goals" %}:</strong></p>

    {% for goal in goals %}
        <p>{{ goal.player.name }}</p>
    {% endfor %}
    
{% endblock %}

apps/templates/matches/match_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Football{% endblock title %}

{% block content %}
    <h1>{% trans "Matches" %}</h1>
    
    <div class="list-group">
        {% for match in matches %}
            <a href="{% url "matches:match-detail" pk=match.id %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                {{ match }}
                <span class="badge badge-primary badge-pill">{{ match.score }}</span>
            </a>
        {% empty %}
            {% trans "No registered matches yet." %}
        {% endfor %}
    </div>
    
{% endblock %}

apps/templates/matches/matches_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Match" %}{% endblock title %}

{% block content %}
    <h1>{{ object }}</h1>
    <br>
    <p><strong>{% trans "Goals" %}:</strong></p>

    {% for goal in goals %}
        <p>{{ goal.player.name }}</p>
    {% endfor %}
    
{% endblock %}

apps/templates/matches/matches_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Wedstrijden{% endblock title %}

{% block content %}
    <h1>Wedstrijden</h1>
    
    <div class="list-group">
        {% for match in matches %}
            <a href="{% url "matches:match-detail" pk=match.id %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                {{ match }}
                <span class="badge badge-primary badge-pill">{{ match.score }}</span>
            </a>
        {% endfor %}
    </div>
    
{% endblock %}